In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r'Dataset.csv',encoding='latin1')

In [3]:
dataset

CASE_SUBMITTED_DAY  CASE_SUBMITTED_MONTH  CASE_SUBMITTED_YEAR  \
0                     24                     2                 2016   
1                      4                     3                 2016   
2                     10                     3                 2016   
3                     28                     9                 2016   
4                     22                     2                 2015   
...                  ...                   ...                  ...   
9994                   5                    10                 2016   
9995                   5                    10                 2016   
9996                   5                    10                 2016   
9997                   5                    10                 2016   
9998                   5                    10                 2016   

      DECISION_DAY  DECISION_MONTH  DECISION_YEAR VISA_CLASS  \
0                1              10           2016        H1B   
1                1              10           2016        H1B   
2                1              10           2016        H1B   
3                1              10           2016        H1B   
4                2              10           2016        H1B   
...            ...             ...            ...        ...   
9994            12              10           2016        H1B   
9995            12              10           2016        H1B   
9996            12              10           2016        H1B   
9997            12              10           2016        H1B   
9998            12              10           2016        H1B   

                          EMPLOYER_NAME EMPLOYER_STATE  \
0                 DISCOVER PRODUCTS INC             IL   
1                      DFS SERVICES LLC             IL   
2             EASTBANC TECHNOLOGIES LLC             DC   
3                     INFO SERVICES LLC             MI   
4                    BBandT CORPORATION             NC   
...                                 ...            ...   
9994  TATA CONSULTANCY SERVICES LIMITED             MD   
9995  TATA CONSULTANCY SERVICES LIMITED             MD   
9996  TATA CONSULTANCY SERVICES LIMITED             MD   
9997  TATA CONSULTANCY SERVICES LIMITED             MD   
9998  TATA CONSULTANCY SERVICES LIMITED             MD   

              EMPLOYER_COUNTRY  ... PW_SOURCE_YEAR  \
0     UNITED STATES OF AMERICA  ...         2015.0   
1     UNITED STATES OF AMERICA  ...         2015.0   
2     UNITED STATES OF AMERICA  ...         2015.0   
3     UNITED STATES OF AMERICA  ...         2016.0   
4     UNITED STATES OF AMERICA  ...         2015.0   
...                        ...  ...            ...   
9994  UNITED STATES OF AMERICA  ...         2016.0   
9995  UNITED STATES OF AMERICA  ...         2016.0   
9996  UNITED STATES OF AMERICA  ...         2016.0   
9997  UNITED STATES OF AMERICA  ...         2016.0   
9998  UNITED STATES OF AMERICA  ...         2016.0   

                  PW_SOURCE_OTHER  WAGE_RATE_OF_PAY_FROM WAGE_RATE_OF_PAY_TO  \
0         OFLC ONLINE DATA CENTER                65811.0             67320.0   
1     WILLIS TOWERS WATSON SURVEY                53000.0             57200.0   
2         OFLC ONLINE DATA CENTER                77000.0                 0.0   
3         OFLC ONLINE DATA CENTER               102000.0                 0.0   
4         OFLC ONLINE DATA CENTER               132500.0                 0.0   
...                           ...                    ...                 ...   
9994      OFLC ONLINE DATA CENTER                71261.0             87000.0   
9995      OFLC ONLINE DATA CENTER                74173.0             94500.0   
9996      OFLC ONLINE DATA CENTER                65645.0             86000.0   
9997      OFLC ONLINE DATA CENTER                60700.0             87000.0   
9998      OFLC ONLINE DATA CENTER                68557.0             94500.0   

      WAGE_UNIT_OF_PAY H-1B_DEPENDENT WILLFUL_VIOLATOR  WORKSITE_STATE  \
0  

In [4]:
dataset.isnull().any()

CASE_SUBMITTED_DAY       False
CASE_SUBMITTED_MONTH     False
CASE_SUBMITTED_YEAR      False
DECISION_DAY             False
DECISION_MONTH           False
DECISION_YEAR            False
VISA_CLASS               False
EMPLOYER_NAME             True
EMPLOYER_STATE           False
EMPLOYER_COUNTRY         False
SOC_NAME                 False
NAICS_CODE               False
TOTAL_WORKERS            False
FULL_TIME_POSITION       False
PREVAILING_WAGE          False
PW_UNIT_OF_PAY            True
PW_SOURCE                 True
PW_SOURCE_YEAR            True
PW_SOURCE_OTHER          False
WAGE_RATE_OF_PAY_FROM    False
WAGE_RATE_OF_PAY_TO      False
WAGE_UNIT_OF_PAY         False
H-1B_DEPENDENT            True
WILLFUL_VIOLATOR          True
WORKSITE_STATE           False
WORKSITE_POSTAL_CODE     False
CASE_STATUS              False
dtype: bool

In [5]:
dataset['H-1B_DEPENDENT'].fillna('Y', inplace=True)

In [6]:
dataset['WILLFUL_VIOLATOR'].fillna('N', inplace=True)

In [7]:
dataset['EMPLOYER_NAME'].fillna('INFOSYS LIMITED', inplace=True)

In [8]:
dataset['PW_UNIT_OF_PAY'].fillna('Year', inplace=True)

In [9]:
dataset['PW_SOURCE'].fillna('OES', inplace=True)

In [10]:
dataset['PW_SOURCE_YEAR'].fillna(dataset['PW_SOURCE_YEAR'].mean(), inplace=True)

In [11]:
dataset.isnull().any()

CASE_SUBMITTED_DAY       False
CASE_SUBMITTED_MONTH     False
CASE_SUBMITTED_YEAR      False
DECISION_DAY             False
DECISION_MONTH           False
DECISION_YEAR            False
VISA_CLASS               False
EMPLOYER_NAME            False
EMPLOYER_STATE           False
EMPLOYER_COUNTRY         False
SOC_NAME                 False
NAICS_CODE               False
TOTAL_WORKERS            False
FULL_TIME_POSITION       False
PREVAILING_WAGE          False
PW_UNIT_OF_PAY           False
PW_SOURCE                False
PW_SOURCE_YEAR           False
PW_SOURCE_OTHER          False
WAGE_RATE_OF_PAY_FROM    False
WAGE_RATE_OF_PAY_TO      False
WAGE_UNIT_OF_PAY         False
H-1B_DEPENDENT           False
WILLFUL_VIOLATOR         False
WORKSITE_STATE           False
WORKSITE_POSTAL_CODE     False
CASE_STATUS              False
dtype: bool

In [12]:
dataset['CASE_STATUS'].replace(['CERTIFIED','CERTIFIEDWITHDRAWN','WITHDRAWN','DENIED'],[1,0,2,3],inplace=True)

In [13]:
dataset

CASE_SUBMITTED_DAY  CASE_SUBMITTED_MONTH  CASE_SUBMITTED_YEAR  \
0                     24                     2                 2016   
1                      4                     3                 2016   
2                     10                     3                 2016   
3                     28                     9                 2016   
4                     22                     2                 2015   
...                  ...                   ...                  ...   
9994                   5                    10                 2016   
9995                   5                    10                 2016   
9996                   5                    10                 2016   
9997                   5                    10                 2016   
9998                   5                    10                 2016   

      DECISION_DAY  DECISION_MONTH  DECISION_YEAR VISA_CLASS  \
0                1              10           2016        H1B   
1                1              10           2016        H1B   
2                1              10           2016        H1B   
3                1              10           2016        H1B   
4                2              10           2016        H1B   
...            ...             ...            ...        ...   
9994            12              10           2016        H1B   
9995            12              10           2016        H1B   
9996            12              10           2016        H1B   
9997            12              10           2016        H1B   
9998            12              10           2016        H1B   

                          EMPLOYER_NAME EMPLOYER_STATE  \
0                 DISCOVER PRODUCTS INC             IL   
1                      DFS SERVICES LLC             IL   
2             EASTBANC TECHNOLOGIES LLC             DC   
3                     INFO SERVICES LLC             MI   
4                    BBandT CORPORATION             NC   
...                                 ...            ...   
9994  TATA CONSULTANCY SERVICES LIMITED             MD   
9995  TATA CONSULTANCY SERVICES LIMITED             MD   
9996  TATA CONSULTANCY SERVICES LIMITED             MD   
9997  TATA CONSULTANCY SERVICES LIMITED             MD   
9998  TATA CONSULTANCY SERVICES LIMITED             MD   

              EMPLOYER_COUNTRY  ... PW_SOURCE_YEAR  \
0     UNITED STATES OF AMERICA  ...         2015.0   
1     UNITED STATES OF AMERICA  ...         2015.0   
2     UNITED STATES OF AMERICA  ...         2015.0   
3     UNITED STATES OF AMERICA  ...         2016.0   
4     UNITED STATES OF AMERICA  ...         2015.0   
...                        ...  ...            ...   
9994  UNITED STATES OF AMERICA  ...         2016.0   
9995  UNITED STATES OF AMERICA  ...         2016.0   
9996  UNITED STATES OF AMERICA  ...         2016.0   
9997  UNITED STATES OF AMERICA  ...         2016.0   
9998  UNITED STATES OF AMERICA  ...         2016.0   

                  PW_SOURCE_OTHER  WAGE_RATE_OF_PAY_FROM WAGE_RATE_OF_PAY_TO  \
0         OFLC ONLINE DATA CENTER                65811.0             67320.0   
1     WILLIS TOWERS WATSON SURVEY                53000.0             57200.0   
2         OFLC ONLINE DATA CENTER                77000.0                 0.0   
3         OFLC ONLINE DATA CENTER               102000.0                 0.0   
4         OFLC ONLINE DATA CENTER               132500.0                 0.0   
...                           ...                    ...                 ...   
9994      OFLC ONLINE DATA CENTER                71261.0             87000.0   
9995      OFLC ONLINE DATA CENTER                74173.0             94500.0   
9996      OFLC ONLINE DATA CENTER                65645.0             86000.0   
9997      OFLC ONLINE DATA CENTER                60700.0             87000.0   
9998      OFLC ONLINE DATA CENTER                68557.0             94500.0   

      WAGE_UNIT_OF_PAY H-1B_DEPENDENT WILLFUL_VIOLATOR  WORKSITE_STATE  \
0  

In [14]:
dataset.corr()

CASE_SUBMITTED_DAY  CASE_SUBMITTED_MONTH  \
CASE_SUBMITTED_DAY               1.000000             -0.174484   
CASE_SUBMITTED_MONTH            -0.174484              1.000000   
CASE_SUBMITTED_YEAR              0.031025              0.401221   
DECISION_DAY                    -0.698528              0.193863   
DECISION_MONTH                        NaN                   NaN   
DECISION_YEAR                         NaN                   NaN   
NAICS_CODE                       0.014179             -0.059391   
TOTAL_WORKERS                   -0.019255              0.065848   
PREVAILING_WAGE                 -0.000213              0.104729   
PW_SOURCE_YEAR                   0.037449              0.571572   
WAGE_RATE_OF_PAY_FROM            0.003896              0.089900   
WAGE_RATE_OF_PAY_TO              0.032544              0.053714   
WORKSITE_POSTAL_CODE             0.008968              0.095197   
CASE_STATUS                     -0.015058              0.594205   

                       CASE_SUBMITTED_YEAR  DECISION_DAY  DECISION_MONTH  \
CASE_SUBMITTED_DAY                0.031025     -0.698528             NaN   
CASE_SUBMITTED_MONTH              0.401221      0.193863             NaN   
CASE_SUBMITTED_YEAR               1.000000     -0.013158             NaN   
DECISION_DAY                     -0.013158      1.000000             NaN   
DECISION_MONTH                         NaN           NaN             NaN   
DECISION_YEAR                          NaN           NaN             NaN   
NAICS_CODE                       -0.046884     -0.019198             NaN   
TOTAL_WORKERS                     0.050396      0.015599             NaN   
PREVAILING_WAGE                   0.088398      0.005976             NaN   
PW_SOURCE_YEAR                    0.777811      0.008007             NaN   
WAGE_RATE_OF_PAY_FROM             0.079064     -0.001040             NaN   
WAGE_RATE_OF_PAY_TO               0.029397     -0.024850             NaN   
WORKSITE_POSTAL_CODE              0.017062     -0.003576             NaN   
CASE_STATUS                       0.406411     -0.012458             NaN   

                       DECISION_YEAR  NAICS_CODE  TOTAL_WORKERS  \
CASE_SUBMITTED_DAY               NaN    0.014179      -0.019255   
CASE_SUBMITTED_MONTH             NaN   -0.059391       0.065848   
CASE_SUBMITTED_YEAR              NaN   -0.046884       0.050396   
DECISION_DAY                     NaN   -0.019198       0.015599   
DECISION_MONTH                   NaN         NaN            NaN   
DECISION_YEAR                    NaN         NaN            NaN   
NAICS_CODE                       NaN    1.000000      -0.221909   
TOTAL_WORKERS                    NaN   -0.221909       1.000000   
PREVAILING_WAGE                  NaN   -0.089006       0.010507   
PW_SOURCE_YEAR                   NaN   -0.034464       0.058678   
WAGE_RATE_OF_PAY_FROM            NaN   -0.065987      -0.009017   
WAGE_RATE_OF_PAY_TO              NaN   -0.121049       0.223286   
WORKSITE_POSTAL_CODE             NaN   -0.056767      -0.000395   
CASE_STATUS                      NaN   -0.063571       0.036866   

                       PREVAILING_WAGE  PW_SOURCE_YEAR  WAGE_RATE_OF_PAY_FROM  \
CASE_SUBMITTED_DAY           -0.000213        0.037449               0.003896   
CASE_SUBMITTED_MONTH          0.104729        0.571572               0.089900   
CASE_SUBMITTED_YEAR           0.088398        0.777811               0.079064   
DECISION_DAY                  0.005976        0.008007              -0.001040   
DECISION_MONTH                     NaN             NaN                    NaN   
DECISION_YEAR                      NaN             NaN                    NaN   
NAICS_CODE                   -0.089006       -0.034464              -0.065987   
TOTAL_WORKERS                 0.010507        0.058678              -0.009017   
PREVAILING_WAGE               1.000000        0.096508               0.872258   
PW_SOURCE_YEAR                0.096508        1.000000      

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   CASE_SUBMITTED_DAY     9999 non-null   int64  
 1   CASE_SUBMITTED_MONTH   9999 non-null   int64  
 2   CASE_SUBMITTED_YEAR    9999 non-null   int64  
 3   DECISION_DAY           9999 non-null   int64  
 4   DECISION_MONTH         9999 non-null   int64  
 5   DECISION_YEAR          9999 non-null   int64  
 6   VISA_CLASS             9999 non-null   object 
 7   EMPLOYER_NAME          9999 non-null   object 
 8   EMPLOYER_STATE         9999 non-null   object 
 9   EMPLOYER_COUNTRY       9999 non-null   object 
 10  SOC_NAME               9999 non-null   object 
 11  NAICS_CODE             9999 non-null   int64  
 12  TOTAL_WORKERS          9999 non-null   int64  
 13  FULL_TIME_POSITION     9999 non-null   object 
 14  PREVAILING_WAGE        9999 non-null   float64
 15  PW_U

In [16]:
x=dataset.iloc[:,6:27]

In [17]:
x

VISA_CLASS                      EMPLOYER_NAME EMPLOYER_STATE  \
0           H1B              DISCOVER PRODUCTS INC             IL   
1           H1B                   DFS SERVICES LLC             IL   
2           H1B          EASTBANC TECHNOLOGIES LLC             DC   
3           H1B                  INFO SERVICES LLC             MI   
4           H1B                 BBandT CORPORATION             NC   
...         ...                                ...            ...   
9994        H1B  TATA CONSULTANCY SERVICES LIMITED             MD   
9995        H1B  TATA CONSULTANCY SERVICES LIMITED             MD   
9996        H1B  TATA CONSULTANCY SERVICES LIMITED             MD   
9997        H1B  TATA CONSULTANCY SERVICES LIMITED             MD   
9998        H1B  TATA CONSULTANCY SERVICES LIMITED             MD   

              EMPLOYER_COUNTRY             SOC_NAME  NAICS_CODE  \
0     UNITED STATES OF AMERICA             ANALYSTS      522210   
1     UNITED STATES OF AMERICA             ANALYSTS      522210   
2     UNITED STATES OF AMERICA             ANALYSTS      541511   
3     UNITED STATES OF AMERICA  COMPUTER OCCUPATION      541511   
4     UNITED STATES OF AMERICA             ANALYSTS      522110   
...                        ...                  ...         ...   
9994  UNITED STATES OF AMERICA            ENGINEERS      541511   
9995  UNITED STATES OF AMERICA            ENGINEERS      541511   
9996  UNITED STATES OF AMERICA            ENGINEERS      541511   
9997  UNITED STATES OF AMERICA            ENGINEERS      541511   
9998  UNITED STATES OF AMERICA            ENGINEERS      541511   

      TOTAL_WORKERS FULL_TIME_POSITION  PREVAILING_WAGE PW_UNIT_OF_PAY  ...  \
0                 1                  Y          59197.0           Year  ...   
1                 1                  Y          49800.0           Year  ...   
2                 2                  Y          76502.0           Year  ...   
3                 1                  Y          90376.0           Year  ...   
4                 1                  Y         116605.0           Year  ...   
...             ...                ...              ...            ...  ...   
9994              1                  Y          71261.0           Year  ...   
9995              1                  Y          74173.0           Year  ...   
9996              1                  Y          65645.0           Year  ...   
9997              1                  Y          59322.0           Year  ...   
9998              1                  Y          68557.0           Year  ...   

     PW_SOURCE_YEAR              PW_SOURCE_OTHER WAGE_RATE_OF_PAY_FROM  \
0            2015.0      OFLC ONLINE DATA CENTER               65811.0   
1            2015.0  WILLIS TOWERS WATSON SURVEY               53000.0   
2            2015.0      OFLC ONLINE DATA CENTER               77000.0   
3            2016.0      OFLC ONLINE DATA CENTER              102000.0   
4            2015.0      OFLC ONLINE DATA CENTER              132500.0   
...             ...                          ...                   ...   
9994         2016.0      OFLC ONLINE DATA CENTER               71261.0   
9995         2016.0      OFLC ONLINE DATA CENTER               74173.0   
9996         2016.0      OFLC ONLINE DATA CENTER               65645.0   
9997         2016.0      OFLC ONLINE DATA CENTER               60700.0   
9998         2016.0      OFLC ONLINE DATA CENTER               68557.0   

      WAGE_RATE_OF_PAY_TO  WAGE_UNIT_OF_PAY H-1B_DEPENDENT WILLFUL_VIOLATOR  \
0                 67320.0              Year              N                N   
1                 57200.0              Year              N                N   
2                     0.0              Year              Y                N   
3                     0.0              Year              Y                N   
4                     0.0              Year              N                N   
...                   ...               ...            ... 

In [18]:
x=dataset.iloc[:,6:27].values
y=dataset.iloc[:, 26].values

In [19]:
x

array([['H1B', 'DISCOVER PRODUCTS INC', 'IL', ..., 'IL', 60015, 0],
       ['H1B', 'DFS SERVICES LLC', 'IL', ..., 'IL', 60015, 0],
       ['H1B', 'EASTBANC TECHNOLOGIES LLC', 'DC', ..., 'DC', 20007, 0],
       ...,
       ['H1B', 'TATA CONSULTANCY SERVICES LIMITED', 'MD', ..., 'NJ',
        7310, 1],
       ['H1B', 'TATA CONSULTANCY SERVICES LIMITED', 'MD', ..., 'IN',
        46240, 1],
       ['H1B', 'TATA CONSULTANCY SERVICES LIMITED', 'MD', ..., 'MN',
        55423, 1]], dtype=object)

In [20]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [21]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [22]:
x[:,0]=lb.fit_transform(x[:,0]) #visa class
x[:,1]=lb.fit_transform(x[:,1]) #employer name
x[:,2]=lb.fit_transform(x[:,2]) #employer state
x[:,3]=lb.fit_transform(x[:,3]) #employer country
x[:,4]=lb.fit_transform(x[:,4]) #soc_name
x[:,-3]=lb.fit_transform(x[:,-3])#worksite state
x[:,-4]=lb.fit_transform(x[:,-4])#willfull violator
x[:,-5]=lb.fit_transform(x[:,-5])#h1b dependent
x[:,7]=lb.fit_transform(x[:,7])#full time position
x[:,9]=lb.fit_transform(x[:,9])#pw unit of pay
x[:,10]=lb.fit_transform(x[:,10])#pw source
x[:,12]=lb.fit_transform(x[:,12])#pw source other
x[:,15]=lb.fit_transform(x[:,15])#wage unit of pay

In [23]:
x

array([[1, 948, 15, ..., 15, 60015, 0],
       [1, 924, 15, ..., 15, 60015, 0],
       [1, 1002, 7, ..., 7, 20007, 0],
       ...,
       [1, 3241, 21, ..., 33, 7310, 1],
       [1, 3241, 21, ..., 16, 46240, 1],
       [1, 3241, 21, ..., 24, 55423, 1]], dtype=object)

In [24]:
dataset['CASE_STATUS'].unique()

array([0, 2, 1, 3], dtype=int64)

In [25]:
x=x[:,1:]

In [26]:
x

array([[948, 15, 0, ..., 15, 60015, 0],
       [924, 15, 0, ..., 15, 60015, 0],
       [1002, 7, 0, ..., 7, 20007, 0],
       ...,
       [3241, 21, 0, ..., 33, 7310, 1],
       [3241, 21, 0, ..., 16, 46240, 1],
       [3241, 21, 0, ..., 24, 55423, 1]], dtype=object)

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [28]:
x_test

array([[2167, 20, 0, ..., 20, 2493, 1],
       [3330, 50, 0, ..., 50, 98108, 0],
       [2265, 29, 0, ..., 4, 94538, 0],
       ...,
       [2991, 13, 0, ..., 29, 28092, 1],
       [3300, 36, 0, ..., 36, 10005, 1],
       [262, 4, 0, ..., 4, 95014, 1]], dtype=object)

In [29]:
y_test = y_test.astype('int')
y_test

array([1, 0, 0, ..., 1, 1, 1])

In [30]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

x_train =scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [31]:
x_train

array([[-0.86765229,  0.85195321,  0.        , ..., -1.30514392,
         1.28181049,  0.16526295],
       [ 1.30073581,  1.23509266,  0.        , ...,  1.27725666,
         0.84035937,  0.16526295],
       [ 0.22994894,  1.49051896,  0.        , ...,  1.52319957,
         1.3892072 ,  0.16526295],
       ...,
       [-0.298294  , -0.10589542,  0.        , ...,  1.27725666,
         0.71167762,  0.16526295],
       [ 0.59104902, -0.23360857,  0.        , ..., -0.13691509,
        -0.07448515,  0.16526295],
       [-0.69246513,  0.66038348,  0.        , ..., -0.01394363,
         0.36143127, -1.9912433 ]])

In [32]:
#Random Forest Calssifier
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rf_classi = rmf.fit(x_train, y_train)

In [33]:
rf_y_test = rf_classi.predict(x_test)


In [34]:
from joblib import dump
dump(rmf,'rmf.save')

['rmf.save']

In [35]:
from sklearn.metrics import accuracy_score
rf_accu_test= accuracy_score(y_test,rf_y_test)
rf_accu_test

0.955